services:
  # PostgreSQL Database Service
  postgres_db:
    image: postgres:15-alpine
    container_name: tsi_privacy_vault_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 45s

  # Java Jetty Web Application Service
  jetty_app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: tsi_privacy_vault_jetty
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080 (Jetty's default)
    environment:
      # Database
      POSTGRES_HOST: "jdbc:postgresql://postgres_db:5432"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWD: ${POSTGRES_PASSWD}

      # Global Salt for LookupHasher
      TSI_LOOKUP_SALT: ${TSI_LOOKUP_SALT}
      TSI_PRIVACY_VAULT_ENV: ${TSI_PRIVACY_VAULT_ENV}

      # AWS Credentials for KMS Service (ONLY FOR LOCAL TESTING, NOT FOR PRODUCTION)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_KMS_KEY_IDENTIFIER: ${AWS_KMS_KEY_IDENTIFIER}
    depends_on:
      postgres_db:
        condition: service_healthy
volumes:
  postgres_data: